### PR TITLE
fix Distinct() could not work when different types of values under th…

### LINKED ISSUE #114: fix Distinct() could not work when different types of values

### PR DESCRIPTION
**Pull request by qnxm**
…e same tag

fix #114

### CODE REVIEW

File: query_test.go [hunk 1]
```diff
@@ -380,11 +381,13 @@ func TestQuery_Distinct(t *testing.T) {
 	id2 := primitive.NewObjectID()
 	id3 := primitive.NewObjectID()
 	id4 := primitive.NewObjectID()
+	id5 := primitive.NewObjectID()
 	docs := []interface{}{
 		bson.M{"_id": id1, "name": "Alice", "age": 18},
 		bson.M{"_id": id2, "name": "Alice", "age": 19},
 		bson.M{"_id": id3, "name": "Lucas", "age": 20},
 		bson.M{"_id": id4, "name": "Lucas", "age": 21},
+		bson.M{"_id": id5, "name": "Kitty", "age": 23, "detail": bson.M{"errInfo": "timeout", "extra": "i/o"}},
```
Comment (jiangz222) [inline query_test.go:390]: 直接用自定义结构体会有区别吗？
